# Generated by Django 2.0.9 on 2021-07-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rides_offered',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rides_taken',
        ),
    ]
